name = "interaction"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "testDb"
database_id = "1e6bb61a-cb37-40da-a1da-bb0470304c7b"
